<?php

namespace Modules\Product\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\Files\Entities\File;
use Modules\Initializer\Traits\SortTrait;
use Modules\Initializer\Traits\TableColumnsTrait;
use Modules\Initializer\Traits\RelationTrait;
use Modules\Product\Traits\ProductCategoryActiveTrait;
use Modules\Initializer\Traits\UrlKeyTrait;

//use Fico7489\Laravel\Pivot\Traits\PivotEventTrait;

class ProductCategory extends Model
{
  use SoftDeletes, TableColumnsTrait, RelationTrait, SortTrait, ProductCategoryActiveTrait, UrlKeyTrait;  //, PivotEventTrait;

  protected $dates = ['deleted_at'];

  protected $guarded = [];

  public $cacheModule = 'product';

  public $form = [
    'id' => [
      'enabled' => true
    ],
    'title' => [
      'enabled' => true,
      'validations' => [
        'required' => true,
        'max' => 255
      ]
    ],
    'active' => [
      'enabled' => true
    ],
    'description' => [
      'enabled' => true
    ]
  ];

  public $fields = ['id','title','active','description'];

  public function getRules()
  {
    return [
      'title' => 'required|max:255'
    ];
  }

  protected $table = 'product_categories';

  public function typeProducts() {
    return $this->hasMany(TypeProduct::class);
  }

  public function attributes() {
    return $this->morphToMany('Modules\Product\Entities\Attribute', 'attributable');
  }

  public function products() {
    return $this->hasMany(Product::class);
  }

  public function files() {
    return $this->morphMany(File::class, 'fileable');
  }

  /*protected static function boot()
  {
    parent::boot(); // TODO: Change the autogenerated stub

    static::pivotDetached(function ($model, $relationName, $pivotIds) {
      if($relationName == 'attributes') {
        foreach($povotIds as $attribute_id) {
          $attrubyteValue = AttributeValue::where('attribute_id', $attribute_id)->firstOrFail();
          $attrubyteValue->delete();
        }
      }
    });
  }*/
}
